Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -21,25 +21,22 @@ update:
     - curl -sS https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
     - export PATH="$HOME/.elan/bin:$PATH"
   script:
-    - git checkout master; git pull
+    - git checkout master && git pull
     - RELEASE_TAG=$(curl -s "https://api.github.com/repos/leanprover/lean4/releases" | jq -r '.[0].tag_name')
     - echo "Latest Lean version is $RELEASE_TAG"
+    - grep -q "leanprover/lean4:${RELEASE_TAG}" lean-toolchain && echo "Lean version ${RELEASE_TAG} is already in use." && exit 0
     - |
-      if ! grep -q "leanprover/lean4:${RELEASE_TAG}" lean-toolchain; then
-        ISSUE_EXISTS=$(curl -s --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" "https://gitlab.com/api/v4/projects/2411/issues?search=Lean update to $RELEASE_TAG failed" | jq '. | length')
-        if [ "$ISSUE_EXISTS" -eq "0" ]; then
-          echo "leanprover/lean4:${RELEASE_TAG}" > lean-toolchain
-          if ! (lake clean && lake update && lake exe cache get && lake build); then
-            curl --request POST --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" --data "title=Lean update to $RELEASE_TAG failed" --data "description=An attempt to update to Lean version $RELEASE_TAG failed during build." "https://gitlab.com/api/v4/projects/2411/issues"
-          else
-            git add -A
-            git commit -m "Updated Lean toolchain to $RELEASE_TAG"
-            git push origin master
-          fi
-        else
-          echo "Update to ${RELEASE_TAG} previously failed"
-        fi
+      if [ $(curl -s --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" "https://gitlab.com/api/v4/projects/2411/issues?search=Lean update to $RELEASE_TAG failed" | jq '. | length') -ne 0 ]; then
+        echo "Update to ${RELEASE_TAG} previously failed, issue already exists."
+        exit 0
       fi
+    - echo "leanprover/lean4:${RELEASE_TAG}" > lean-toolchain
+    - |
+      if ! (lake clean && lake update && lake exe cache get && lake build); then
+        curl --request POST --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" --data "title=Lean update to $RELEASE_TAG failed" --data "description=An attempt to update to Lean version $RELEASE_TAG failed during build." "https://gitlab.com/api/v4/projects/2411/issues"
+        exit 0
+      fi
+    - git add -A && git commit -m "Updated Lean toolchain to $RELEASE_TAG" && git push origin master
 
 mirror:
   stage: mirror
