Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -26,8 +26,19 @@ update:
     - echo "Latest Lean version is $RELEASE_TAG"
     - |
       if ! grep -q "leanprover/lean4:${RELEASE_TAG}" lean-toolchain; then
-        echo "leanprover/lean4:${RELEASE_TAG}" > lean-toolchain
-        lake clean && lake update && lake exe cache get && lake build
+        ISSUE_EXISTS=$(curl -s --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" "https://gitlab.com/api/v4/projects/2411/issues?search=Lean pdate to $RELEASE_TAG failed" | jq '. | length')
+        if [ "$ISSUE_EXISTS" -ne "0" ]; then
+          echo "leanprover/lean4:${RELEASE_TAG}" > lean-toolchain
+          if ! (lake clean && lake update && lake exe cache get && lake build); then
+            curl --request POST --header "PRIVATE-TOKEN: ${UPDATE_TOKEN}" --data "title=Lean udate to $RELEASE_TAG failed" --data "description=An attempt to update to Lean version $RELEASE_TAG failed during build." "https://gitlab.com/api/v4/projects/2411/issues"
+          else
+            git add -A
+            git commit -m "Updated Lean toolchain to $RELEASE_TAG"
+            git push origin master
+          fi
+        else
+          echo "Update to ${RELEASE_TAG} previously failed"
+        fi
       fi
 
 mirror:
