Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -32,14 +32,20 @@ update:
       if [ "$issue_matches" -ne 0 ]; then echo "Update to ${RELEASE_TAG} previously failed, issue already exists." && exit 0; fi
     - sed -i 's|\("https://github.com/leanprover-community/mathlib4.git"@\)"[^"]*"|\1"$RELEASE_TAG"|' lakefile.lean
     - |
-      OUTPUT=$(lake clean && lake update && lake exe cache get && lake build 2>&1) || {
-        ERROR_MSG=$(echo -e "An attempt to update to Lean version $RELEASE_TAG failed during build. Error output: \n \`\`\`$OUTPUT\`\`\`")
+      OUTPUT=$(lake clean && lake update && lake exe cache get && lake build 2>&1)
+      BUILD_EXIT_CODE=$?
+
+      if [ "$BUILD_EXIT_CODE" -ne 0 ]; then
+        ERROR_MSG=$(echo -e "An attempt to update to Lean version $RELEASE_TAG failed during build. Error output: \n $OUTPUT")
         curl --request POST --header "PRIVATE-TOKEN: ${UPDATE_PIPELINE}" \
             --data-urlencode "title=mathlib4 update to $RELEASE_TAG failed" \
             --data-urlencode "description=${ERROR_MSG}" \
             "https://git.zib.de/api/v4/projects/2411/issues" || exit 1
-        exit 0
-      }
+      else
+        echo "Build successful."
+      fi
+
+      exit 0
     - |
       git config --global user.email "spiegel@zib.de"
       git config --global user.name "Auto Update"
